import { Router } from "express";
import StreamRoutes from "./StreamRoutes";
import StaffTypeRoutes from "./StaffTypeRoutes";
import StaffRoutes from "./StaffRoutes";
import AuthRoutes from "./AuthRoutes";
import SectionRoutes from "./SectionRoutes";
import ClassRoutes from "./ClassRoutes";
import FeeRoutes from "./FeeRoutes";
import SubjectRoutes from "./SubjectRoutes";
import TermRoutes from "./TermRoutes";
import ExamTypeRoutes from "./ExamTypeRoutes";
import AssessmentRoutes from "./AssessmentRoutes";
import GradeRoutes from "./GradeRoutes";
import StudentRoutes from "./StudentRoutes";
import HouseRoutes from "./HouseRoutes";
import StudentTypeRoutes from "./StudentTypeRoutes";
import PaySlipCategoryRoutes from "./PaySlipCategoryRoutes";
import SalaryInfoRoutes from "./SalaryInfoRoutes";
import PaySlipRoutes from "./PaySlipRoutes";
import SchoolRoutes from "./SchoolRoutes";
import AccountRoutes from "./AccountRoutes";
import JournalRoutes from "./JournalRoutes";
import SupplierRoutes from "./SupplierRoutes";
import StaffProfileRoutes from "./StaffProfileRoutes";
import TransactionTypeRoutes from "./TransactionTypeRoutes";
import TransactionRoutes from "./TransactionRoutes";
import DivisionRoutes from "./DivisionRoutes";
import StudentFeePaymentRoutes from "./StudentFeePaymentRoutes";
import ReportRoutes from "./ReportRoutes";
import StockTypeRoutes from "./StockTypeRoutes";
import StockLevelRoutes from "./StockLevelRoutes";
import ReductionRoutes from "./ReductionRoutes";
import SystemRoutes from "./SystemRoutes";
import ClassLevelRoutes from "./ClassLevelRoutes";
import CategoriesRoutes from "./CategoriesRoutes";
import StockRoutes from "./StockRoutes";
import ExpensesRoutes from "./ExpensesRoutes";
import SalesRoutes from "./SalesRoutes";
import CustomerRoutes from "./CustomerRoutes";

const router = Router();

export default (): Router => {
  StaffTypeRoutes(router);
  StaffRoutes(router);
  AuthRoutes(router);
  JournalRoutes(router);
  SupplierRoutes(router);
  StaffProfileRoutes(router);
  TransactionTypeRoutes(router);
  TransactionRoutes(router);
  CategoriesRoutes(router);
  StockRoutes(router);
  ExpensesRoutes(router);
  SalesRoutes(router);
  CustomerRoutes(router);
  return router;
};
