import { Router } from "express";
import StreamRoutes from "./StreamRoutes";
import StaffTypeRoutes from "./StaffTypeRoutes";
import StaffRoutes from "./StaffRoutes";
import AuthRoutes from "./AuthRoutes";
import SectionRoutes from "./SectionRoutes";
import ClassRoutes from "./ClassRoutes";
import FeeRoutes from "./FeeRoutes";
import SubjectRoutes from "./SubjectRoutes";
import TermRoutes from "./TermRoutes";
import ExamTypeRoutes from "./ExamTypeRoutes";
import AssessmentRoutes from "./AssessmentRoutes";
import GradeRoutes from "./GradeRoutes";
import StudentRoutes from "./StudentRoutes";
import HouseRoutes from "./HouseRoutes";
import StudentTypeRoutes from "./StudentTypeRoutes";
import PaySlipCategoryRoutes from "./PaySlipCategoryRoutes";
import SalaryInfoRoutes from "./SalaryInfoRoutes";
import PaySlipRoutes from "./PaySlipRoutes";
import SchoolRoutes from "./SchoolRoutes";
import AccountRoutes from "./AccountRoutes";
import JournalRoutes from "./JournalRoutes";
import SupplierRoutes from "./SupplierRoutes";

const router = Router();

export default (): Router => {
  StreamRoutes(router);
  StaffTypeRoutes(router);
  StaffRoutes(router);
  AuthRoutes(router);
  SectionRoutes(router);
  ClassRoutes(router);
  FeeRoutes(router);
  SubjectRoutes(router);
  TermRoutes(router);
  ExamTypeRoutes(router);
  AssessmentRoutes(router);
  GradeRoutes(router);
  StudentRoutes(router);
  HouseRoutes(router);
  StudentTypeRoutes(router);
  PaySlipCategoryRoutes(router);
  SalaryInfoRoutes(router);
  PaySlipRoutes(router);
  SchoolRoutes(router);
  AccountRoutes(router);
  JournalRoutes(router);
  SupplierRoutes(router);
  return router;
};
